#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

use serde_json::{json, Value};
use std::{
    collections::HashMap,
    io::{BufRead, BufReader, Write},
    path::PathBuf,
    process::{Child, ChildStdin, Command, Stdio},
    sync::{
        atomic::{AtomicBool, AtomicU64, Ordering},
        Arc, Mutex,
    },
};
use tauri::{Emitter, Manager};
use tokio::sync::oneshot;

type Pending = Arc<Mutex<HashMap<u64, oneshot::Sender<Result<Value, Value>>>>>;

struct Engine {
    input: Mutex<ChildStdin>,
    child: Mutex<Child>,
    pending: Pending,
    alive: Arc<AtomicBool>,
    next: AtomicU64,
}

fn data_dir(app: &tauri::AppHandle) -> PathBuf {
    std::env::var_os("FOLUMA_DATA")
        .map(PathBuf::from)
        .unwrap_or_else(|| app.path().app_data_dir().expect("app data directory"))
}

fn start_engine(app: &tauri::AppHandle) -> Result<Engine, Box<dyn std::error::Error>> {
    let data = data_dir(app);
    std::fs::create_dir_all(&data)?;
    let mut command = if cfg!(debug_assertions) {
        let root = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .parent()
            .unwrap()
            .to_path_buf();
        let python = if cfg!(windows) {
            ".venv/Scripts/python.exe"
        } else {
            ".venv/bin/python"
        };
        let mut c = Command::new(root.join(python));
        c.args(["-m", "foluma"]).current_dir(root);
        c
    } else {
        let name = if cfg!(windows) {
            "foluma-engine.exe"
        } else {
            "foluma-engine"
        };
        Command::new(app.path().resource_dir()?.join("engine").join(name))
    };
    command
        .arg("--serve")
        .env("FOLUMA_DATA", &data)
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::from(
            std::fs::OpenOptions::new()
                .create(true)
                .append(true)
                .open(data.join("engine.log"))?,
        ));
    if std::env::args().any(|a| a == "--safe-mode") {
        command.arg("--safe-mode");
    }
    let mut child = command.spawn()?;
    let input = child.stdin.take().ok_or("missing engine stdin")?;
    let output = child.stdout.take().ok_or("missing engine stdout")?;
    let pending: Pending = Arc::new(Mutex::new(HashMap::new()));
    let alive = Arc::new(AtomicBool::new(true));
    let reader_pending = pending.clone();
    let reader_alive = alive.clone();
    let handle = app.clone();
    std::thread::spawn(move || {
        for line in BufReader::new(output).lines() {
            let Ok(line) = line else { break };
            let Ok(message) = serde_json::from_str::<Value>(&line) else {
                continue;
            };
            if let Some(id) = message["id"].as_u64() {
                if let Some(sender) = reader_pending.lock().unwrap().remove(&id) {
                    let result = if let Some(error) = message.get("error") {
                        Err(error.clone())
                    } else {
                        Ok(message["result"].clone())
                    };
                    let _ = sender.send(result);
                }
            } else if message.get("method").is_some() {
                let _ = handle.emit("engine-event", message);
            }
        }
        reader_alive.store(false, Ordering::SeqCst);
        for (_, sender) in reader_pending.lock().unwrap().drain() {
            let _ = sender.send(Err(json!({"message": "The conversion engine stopped. Please restart Foluma."})));
        }
        let _ = handle.emit("engine-exit", ());
    });
    Ok(Engine {
        input: Mutex::new(input),
        child: Mutex::new(child),
        pending,
        alive,
        next: AtomicU64::new(1),
    })
}

#[tauri::command]
async fn engine_call(
    engine: tauri::State<'_, Engine>,
    method: String,
    params: Value,
) -> Result<Value, Value> {
    let id = engine.next.fetch_add(1, Ordering::Relaxed);
    let (sender, receiver) = oneshot::channel();
    {
        let mut pending = engine.pending.lock().unwrap();
        if !engine.alive.load(Ordering::SeqCst) {
            return Err(json!({"message": "Engine is disconnected. Please restart."}));
        }
        pending.insert(id, sender);
    }
    let request = json!({"jsonrpc": "2.0", "id": id, "method": method, "params": params});
    if let Err(error) = writeln!(engine.input.lock().unwrap(), "{}", request) {
        engine.pending.lock().unwrap().remove(&id);
        return Err(json!({"message": error.to_string()}));
    }
    receiver
        .await
        .map_err(|e| json!({"message": e.to_string()}))?
}

#[tauri::command]
fn restart_app(app: tauri::AppHandle) {
    app.restart();
}

fn resource(app: &tauri::AppHandle, path: &str) -> Option<(Vec<u8>, &'static str)> {
    // Resource names are generated by the engine, never arbitrary filesystem paths.
    let path = percent_encoding::percent_decode_str(path)
        .decode_utf8()
        .ok()?;
    if path.contains('\\') || path.contains('\0') {
        return None;
    }
    let relative = path.trim_start_matches('/');
    if !(relative.starts_with("previews/") || relative.starts_with("plugins/")) {
        return None;
    }
    let root = data_dir(app).canonicalize().ok()?;
    let file = root.join(relative).canonicalize().ok()?;
    let scope = if relative.starts_with("previews/") {
        root.join("previews")
    } else {
        root.join("plugins")
    };
    if !file.starts_with(scope) || !file.is_file() {
        return None;
    }
    let mime = match file.extension()?.to_str()? {
        "js" | "mjs" => "text/javascript",
        "css" => "text/css",
        "png" => "image/png",
        "jpg" | "jpeg" => "image/jpeg",
        "svg" => "image/svg+xml",
        "woff2" => "font/woff2",
        _ => return None,
    };
    Some((std::fs::read(file).ok()?, mime))
}

fn main() {
    let app = tauri::Builder::default()
        .plugin(tauri_plugin_dialog::init())
        .plugin(tauri_plugin_opener::init())
        .invoke_handler(tauri::generate_handler![engine_call, restart_app])
        .register_uri_scheme_protocol("foluma", |context, request| {
            let found = resource(context.app_handle(), request.uri().path());
            let (status, body, mime) = match found {
                Some((body, mime)) => (200, body, mime),
                None => (404, b"Not found".to_vec(), "text/plain"),
            };
            tauri::http::Response::builder()
                .status(status)
                .header("Content-Type", mime)
                .header("Access-Control-Allow-Origin", "*")
                .header("Cache-Control", "no-cache")
                .body(body)
                .unwrap()
        })
        .setup(|app| {
            let engine = start_engine(app.handle())?;
            app.manage(engine);
            Ok(())
        })
        .build(tauri::generate_context!())
        .expect("Foluma could not start");
    app.run(|app, event| {
        if matches!(event, tauri::RunEvent::Exit) {
            if let Some(engine) = app.try_state::<Engine>() {
                let mut child = engine.child.lock().unwrap();
                // Give Python time to cancel its workers before stopping the engine.
                let _ = writeln!(
                    engine.input.lock().unwrap(),
                    "{{\"jsonrpc\":\"2.0\",\"id\":0,\"method\":\"app.shutdown\"}}"
                );
                for _ in 0..30 {
                    if child.try_wait().ok().flatten().is_some() {
                        break;
                    }
                    std::thread::sleep(std::time::Duration::from_millis(100));
                }
                if child.try_wait().ok().flatten().is_none() {
                    let _ = child.kill();
                }
                let _ = child.wait();
            }
        }
    });
}
